/**
 * The catalogue the app ships.
 *
 * One import for everything that needs "all the references": the shell, and
 * the tests that need realistic data to render against. Nothing downstream
 * names `references.ts` or `catalog.generated.ts`, so the source of the
 * catalogue changes here and nowhere else.
 *
 * The curated catalogue, generated by `npm run catalog:build` from
 * catalog/approved/. Switched from the placeholder illustrations on
 * 29/09/2026, once it cleared the coverage floor in scripts/catalog/coverage.ts
 * in every subject, time band and difficulty. The placeholders stay in
 * references.ts, where component tests that need a tiny, stable catalogue can
 * still use them.
 */

export { CATALOG as CATALOGUE } from "./catalog.generated";
